### PR TITLE
Prepare to publish wasm version to npm.

### PR DESCRIPTION
**Pull request by hildjj**
I've updated Cargo.toml to have the correct name and URLs, added myself to the authors, and dropped a quick `create_wasm.sh` shell script so we don't have to remember how to run wasm-pack.  My plan is to publish the generated  `pkg` directory once this accepted.  @florianb if you'd like to do the publish yourself, that would be even better, in my opinion, since this repo is under your name.  The steps are:

- Ensure you have an npm [account](https://www.npmjs.com/signup)
- Turn on 2FA for your npm account
- Ensure you have node/npm [installed](https://nodejs.org/en/download/current/)
- Log in to npm on the command line with `npm login --auth-type web`
- `./create-wasm.sh`
- `cd pkg`
- Double-check `package.json` looks correct
- `npm pack --dry-run` to see what will go into the package
- `npm publish`

What this will do:
- Builds wasm from the rust code
- Puts a JS wrapper around it that makes it easy to call
- Creates the `package.json` file from `Cargo.toml`
- Publishes a `one-ini` package which will be [here](https://www.npmjs.com/package/one-ini) once you've done all the steps.

(Sorry there's so much detail here.  I assume you've done this before and don't need it, but I added it just in case.)

### CODE REVIEW

**Comment by hildjj** [comment]
The other way I can do this is to make one-ini a submodule of editorconfig-core-js, but this feels more clean and ensures that the LICENSE file sticks with this code.

**Comment by florianb** [comment]
Hey @hildjj - thank you so much for your work!

Is it okay if i am digging into it in tuesday? In germany we have a holiday tomorrow and i really need it.. ;)

I already have a npm account set up - i wonder if it wouldn't be a good idea to put an organization up to handle it?

**Comment by hildjj** [comment]
Some of this is a dup of #18.

**Comment by hildjj** [comment]
Tuesday is just fine!  Thank you.
An org might be a good idea, so we can share permissions.  I can create a `one-ini` and make you co-admin if you'd like.

**Comment by florianb** [comment]
Yeah that would be nice - my npm handle should be florianb as well..

**Comment by hildjj** [comment]
Created https://github.com/one-ini and sent you an invite.  I'll up your authorization level after you accept.  Please transfer this repo there on Tuesday, and we can move forward from there.  Please enjoy your Unity Day holiday.

**Comment by florianb** [comment]
Thank you very much @hildjj! I am going to move it forward - i have to fix an issue with my NPM account first. I come back to you as soon as i published it!

Did you consider trying to make a scoped publication to `@one-ini/...`? As far as i understand the docs: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#publishing-a-package this wouldn't necessarily need the involvement of an NPM-account.

So if you don't mind i'd try that first. I would also go on moving this repo into the one-ini org, to make the names more concise i'd rename this project (having a `@one-ini/one-ini` package feels weird - doesn't it?) to `rust` or `core` since i can image we could derive implementations in other languages as well and `@one-ini/reference` feels so clumsy. Any objections or comments?

**Comment by hildjj** [comment]
Will have a response for you in a few hours, great questions

**Comment by florianb** [comment]
Thanks no worries and no hurry - i already did some preparations. I will transfer and rename the repo tomorrow.


I will then try to publish as GitHub org, i just wanted to collect your concerns if there are any.


Feel free to share your opinion, I'd like to avoid producing you more work than necessary. ;)

________________________________
Von: Joe Hildebrand ***@***.***>
Gesendet: Mittwoch, 5. Oktober 2022 18:53
An: florianb/one-ini
Cc: Florian Neumann; State change
Betreff: Re: [florianb/one-ini] Prepare to publish wasm version to npm. (PR #22)


Will have a response for you in a few hours, great questions

**Pull request merged**
